<a href="https://colab.research.google.com/github/pleachman2021/Data-Science/blob/main/Leachman_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Loops


In [1]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(5,8):
  print (i)

5
6
7


In [3]:
for i in range(3):
  print("Test Number: ", i)

Test Number:  0
Test Number:  1
Test Number:  2


In [4]:
def square(x):
  return x**2

In [5]:
square(5)

25

In [8]:
def add_two(x):
  return x+2

In [9]:
add_two(6)

8

In [11]:
choice = "apple"
if choice =="apple" :
  print("You choose apples")

else:
    print("You did not choose apples")

You choose apples


In [14]:
if choice == "apple":

    print("You choose apples.")

elif choice == "orange":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


##User input

In [17]:
 choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


In [65]:
from IPython.core.display import display, HTML

In [18]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


In [20]:
import numpy as np
import matplotlib.pyplot as plt

In [21]:
cards = np.random.permutation(52)

In [23]:
cards

array([13,  0, 44, 47, 28, 51, 18,  3, 26, 24,  9, 10, 23,  1, 46, 31, 50,
        6, 36, 25, 41, 39, 27, 17, 12, 42, 32, 40,  5, 33,  4, 49,  7, 14,
       43, 29, 48, 22, 45,  2, 34, 30, 16, 20,  8, 19, 15, 38, 11, 21, 35,
       37])

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [24]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [25]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [26]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [27]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [28]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]
  

In [34]:
card_name(1)

'Two of Clubs'

In [49]:
cards = np.random.permutation(52)

In [40]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [44]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Jack of Spades', 'Four of Diamonds', 'Ace of Diamonds')

In [50]:
for i in range(5):
    print(card_name(cards[i]))

Two of Diamonds
Five of Diamonds
Three of Clubs
Six of Clubs
Four of Clubs


In [51]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [62]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']
i = np.random.randint(4)
j = np.random.randint(13)


In [61]:
suit[i]
card[j]

'5'

In [60]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [70]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [71]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [67]:
show_img(img)

In [73]:
for i in range (5):
  img = card_url_head + card_image(i) + card_url_tail
  show_img(img)